### ISSUE TITLE
TcpServer 如何断开客户端的连接呢?

### ISSUE THREAD

**Issue by frozen4** [wlgq2/libuv_cpp11#1]
EventLoop* loop = EventLoop::DefalutLoop();
SocketAddr Addr("0.0.0.0", 10012);
bool AllowConnect=false;
TcpServer Server(loop, Addr);
Server.setNewConnectCallback([&](std::weak_ptr<TcpConnection> session)
{
	if (!AllowConnect)
	{
		session.lock()->close(nullptr);
		return;
	}
});
Server.start();

如果要做IP过滤 或者不允许连接的话应该怎么样断开客户端的连接呢? 我这样做的情况下 虽然客户端连接之后直接就断开连接了 但是Server里面还是有这个连接的 并没有被释放 但是如果我继续连接 超过100次的话 程序就出错关闭了

如果用 Server.closeConnection()的话 也不行 直接宕机

**Comment by wlgq2** [comment]
`client->close([client](std::string& name)
{
    std::cout<<"disconnect socket"<<name<<std::endl;
    delete client;
})`
close函数的回调函数被调用意味着可以安全释放客户端对象。
