### ISSUE TITLE
工程文件或Make文件都没有?

### ISSUE THREAD

**Issue by cuijinquan** [wlgq2/libuv_cpp11#3]
工程文件或Make文件都没有?
是完整可编译的工程吗?

**Comment by wlgq2** [comment]
是完整可编译，不过需要依赖libuv。
这两天会加上工程文件及cmake。

**Comment by wlgq2** [comment]
已更新libuv1.22.0 && vs2017 && gcc7.4.0(linux) 相关工程及组织文件，如需其他版本，则需要自己编译libuv。
