### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Xfusu** [wlgq2/libuv_cpp11#4]
可以提供下工程文件或者CMake文件吗

**Comment by wlgq2** [comment]
已上传 vs2017 win32/x64 && libuv1.22.0 工程.

**Comment by wlgq2** [comment]
已更新 linux环境 gcc7.4.0 && codeblocks 工程组织文件，如需其他版本，则需自己编译libuv。

**Comment by Xfusu** [comment]
好的，非常感谢
